spring.application.name=gestao-financeira-api

spring.datasource.url=${DB_URL}

spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

app.jwt.secret=${JWT_SECRET}

app.jwt.access-expiration-minutes=30
app.jwt.access-expiration-hours=6

app.mail.host=smtp.gmail.com
app.mail.password=Senhas de app de 16 digitos na conta
app.mail.port=587
app.mail.username=exemplo@gmail.com

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.br.com.decodex.gestaofinanceira=DEBUG
logging.level.org.hibernate.SQL=DEBUG
